basePath: /api/v1
definitions:
  common.Response:
    properties:
      code:
        $ref: '#/definitions/e.Code'
      data: {}
      msg:
        type: string
    type: object
  e.Code:
    enum:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
    - 27
    type: integer
    x-enum-comments:
      ErrorAccountInvalid: 用户名或密码错误
      ErrorContextValue: 上下文值传递错误
      ErrorCreateUser: 创建用户错误
      ErrorEmailLinkExpire: 邮件确认链接已过期
      ErrorEncryptMoney: 金额加密错误
      ErrorEncryptPassword: 密码加密错误
      ErrorFileError: 文件错误
      ErrorFileType: 文件类型错误
      ErrorFollowUser: 关注用户失败
      ErrorGenerateToken: token生成错误
      ErrorGetCategoryList: 获取商品分类失败
      ErrorGetFollowerList: 获取粉丝列表失败
      ErrorGetFollowingList: 获取关注列表失败
      ErrorGetUserByID: 根据id获取用户失败
      ErrorIncorrectPassword: 密码错误
      ErrorOSSUploadError: OSS文件上传错误
      ErrorParseToken: token解析错误
      ErrorSendEmail: 发送邮件错误
      ErrorSendEmailTooFrequent: 邮件发送操作频繁
      ErrorUnfollowUser: 取消关注失败
      ErrorUpdateEmail: 更新邮箱错误
      ErrorUpdateUser: 更新用户失败
      ErrorUploadAvatar: 头像上传错误
      ErrorUploadFile: 文件上传错误
      ErrorUserExists: 用户已存在
      InvalidParams: 参数错误
      Success: 响应成功
      UnknownError: 未知错误
    x-enum-varnames:
    - Success
    - InvalidParams
    - UnknownError
    - ErrorUserExists
    - ErrorEncryptPassword
    - ErrorEncryptMoney
    - ErrorCreateUser
    - ErrorAccountInvalid
    - ErrorGetUserByID
    - ErrorUpdateUser
    - ErrorIncorrectPassword
    - ErrorUploadAvatar
    - ErrorFollowUser
    - ErrorUnfollowUser
    - ErrorGetFollowingList
    - ErrorGetFollowerList
    - ErrorGenerateToken
    - ErrorParseToken
    - ErrorContextValue
    - ErrorUploadFile
    - ErrorFileError
    - ErrorOSSUploadError
    - ErrorFileType
    - ErrorSendEmail
    - ErrorUpdateEmail
    - ErrorEmailLinkExpire
    - ErrorSendEmailTooFrequent
    - ErrorGetCategoryList
  response.AuthLoginResp:
    properties:
      access_token:
        type: string
      avatar:
        type: string
      nickname:
        type: string
      refresh_token:
        type: string
    type: object
  response.AuthRegisterResp:
    type: object
  response.BindEmailResp:
    type: object
  response.Category:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  response.Follow:
    properties:
      avatar:
        type: string
      nickname:
        type: string
    type: object
  response.GetCategoryListResp:
    properties:
      list:
        items:
          $ref: '#/definitions/response.Category'
        type: array
      total:
        type: integer
    type: object
  response.ShowUserInfoResp:
    properties:
      avatar:
        type: string
      email:
        type: string
      nickname:
        type: string
      status:
        type: string
      username:
        type: string
    type: object
  response.UploadAvatarResp:
    type: object
  response.UserFollowResp:
    type: object
  response.UserFollowerListResp:
    properties:
      follower:
        items:
          $ref: '#/definitions/response.Follow'
        type: array
    type: object
  response.UserFollowingListResp:
    properties:
      following:
        items:
          $ref: '#/definitions/response.Follow'
        type: array
    type: object
  response.UserInfoUpdateResp:
    type: object
  response.UserPasswordChangeResp:
    type: object
  response.UserUnfollowResp:
    type: object
  response.ValidEmailResp:
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: 1478488313@qq.com
    name: API Support
    url: http://www.swagger.io/support
  description: gin-mall API Documentation
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: gin-mall
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 输入`用户名-密码`以登录
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.AuthLoginResp'
              type: object
      summary: 用户登录
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 输入`用户名-密码-确认密码`以注册
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      - description: 确认密码
        in: formData
        name: confirm_password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.AuthRegisterResp'
              type: object
      summary: 用户注册
      tags:
      - Auth
  /category:
    get:
      consumes:
      - application/json
      description: 获取所有的商品分类
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.GetCategoryListResp'
              type: object
      summary: 获取商品分类列表
      tags:
      - Category
  /user/avatar:
    post:
      consumes:
      - multipart/form-data
      description: 上传头像，文件类型支持jpg(jpeg)、png
      parameters:
      - description: 头像
        in: formData
        name: avatar
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.UploadAvatarResp'
              type: object
      security:
      - AccessToken: []
      - RefreshToken: []
      summary: 上传用户头像
      tags:
      - User
  /user/email/bind:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 发送邮件到用户指定邮箱，用户确认后进行绑定
      parameters:
      - description: 邮箱
        in: formData
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.BindEmailResp'
              type: object
      security:
      - AccessToken: []
      - RefreshToken: []
      summary: 绑定邮箱
      tags:
      - User
  /user/email/valid:
    get:
      description: 通过指定链接确认绑定操作
      parameters:
      - description: email token
        in: query
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.ValidEmailResp'
              type: object
      security:
      - AccessToken: []
      - RefreshToken: []
      summary: 邮箱绑定确认
      tags:
      - User
  /user/follow:
    delete:
      consumes:
      - application/json
      description: 基于id取关用户
      parameters:
      - description: 取关用户的id
        in: body
        name: id
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.UserUnfollowResp'
              type: object
      security:
      - AccessToken: []
      - RefreshToken: []
      summary: 取关用户
      tags:
      - User
    post:
      consumes:
      - application/json
      description: 基于id关注的其他用户
      parameters:
      - description: 关注用户的id
        in: body
        name: id
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.UserFollowResp'
              type: object
      security:
      - AccessToken: []
      - RefreshToken: []
      summary: 关注用户
      tags:
      - User
  /user/follower:
    get:
      consumes:
      - application/json
      description: 获取用户的粉丝列表，列表中的用户信息包括头像和昵称
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.UserFollowerListResp'
              type: object
      security:
      - AccessToken: []
      - RefreshToken: []
      summary: 获取粉丝列表
      tags:
      - User
  /user/following:
    get:
      consumes:
      - application/json
      description: 获取用户的关注列表，列表中的用户信息包括头像和昵称
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.UserFollowingListResp'
              type: object
      security:
      - AccessToken: []
      - RefreshToken: []
      summary: 获取关注列表
      tags:
      - User
  /user/info:
    get:
      consumes:
      - application/json
      description: 可查看信息包括：用户名、昵称、用户状态、邮箱、头像
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.ShowUserInfoResp'
              type: object
      security:
      - AccessToken: []
      - RefreshToken: []
      summary: 查看用户信息
      tags:
      - User
    put:
      consumes:
      - application/x-www-form-urlencoded
      description: 可修改用户昵称
      parameters:
      - description: 昵称
        in: formData
        name: nickname
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.UserInfoUpdateResp'
              type: object
      security:
      - AccessToken: []
      - RefreshToken: []
      summary: 修改用户信息
      tags:
      - User
  /user/password:
    put:
      consumes:
      - application/x-www-form-urlencoded
      description: 输入`原密码-新密码-确认密码`以更改密码
      parameters:
      - description: 原密码
        in: formData
        name: origin_password
        required: true
        type: string
      - description: 新密码
        in: formData
        name: new_password
        required: true
        type: string
      - description: 确认密码
        in: formData
        name: confirm_password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.UserPasswordChangeResp'
              type: object
      security:
      - AccessToken: []
      - RefreshToken: []
      summary: 更改用户密码
      tags:
      - User
securityDefinitions:
  AccessToken:
    in: header
    name: Authorization
    type: apiKey
  RefreshToken:
    in: header
    name: X-Refresh-Token
    type: apiKey
swagger: "2.0"
